// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuXuj6mYkKgCPNp8bshb7WqPz79aaNzU',
    appId: '1:610984604350:web:96cf1db87df4341e91a4ef',
    messagingSenderId: '610984604350',
    projectId: 'fox-link-dev',
    authDomain: 'fox-link-dev.firebaseapp.com',
    storageBucket: 'fox-link-dev.firebasestorage.app',
    measurementId: 'G-SHHYME6CVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-QIkPByRtCIgYI3NtWjmH4QLC3weRV0',
    appId: '1:610984604350:android:be5282f9bb92c33d91a4ef',
    messagingSenderId: '610984604350',
    projectId: 'fox-link-dev',
    storageBucket: 'fox-link-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6z-9SVRTR7fpsyf1VX3UMgJaPBNXJGno',
    appId: '1:610984604350:ios:95c20596b8ce637291a4ef',
    messagingSenderId: '610984604350',
    projectId: 'fox-link-dev',
    storageBucket: 'fox-link-dev.firebasestorage.app',
    iosClientId: '610984604350-3hh9fr9vlto0a5ptvegg15q58k8b0bvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.foxLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6z-9SVRTR7fpsyf1VX3UMgJaPBNXJGno',
    appId: '1:610984604350:ios:95c20596b8ce637291a4ef',
    messagingSenderId: '610984604350',
    projectId: 'fox-link-dev',
    storageBucket: 'fox-link-dev.firebasestorage.app',
    iosClientId: '610984604350-3hh9fr9vlto0a5ptvegg15q58k8b0bvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.foxLinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuuXuj6mYkKgCPNp8bshb7WqPz79aaNzU',
    appId: '1:610984604350:web:783df361bddce09c91a4ef',
    messagingSenderId: '610984604350',
    projectId: 'fox-link-dev',
    authDomain: 'fox-link-dev.firebaseapp.com',
    storageBucket: 'fox-link-dev.firebasestorage.app',
    measurementId: 'G-WG75YQ576M',
  );
}
